#!/bin/sh

WM=bspwm
export WM=$WM

# merge in defaults and keymaps
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/Xresources
sysmodmap=/etc/X11/xinit/Xmodmap

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -n "`/etc/X11/chooser.sh`" ]; then
 command="`/etc/X11/chooser.sh`"
else
 failsafe="yes"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?* ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

if [ -n "$failsafe" ]; then

### NVIDIA CARD
#xrandr --setprovideroutputsource modesetting NVIDIA-0 &
#xrandr --dpi 238 &

xsetroot -cursor_name left_ptr &
xrandr --auto &
exec picom --experimental-backends &
exec pulseaudio --start &
#exec seafile-applet &
#exec /home/wash/.local/share/tresorit/tresorit-daemon &
exec /home/wash/.config/ricescripts/restore-theme &
exec /home/wash/.config/ricescripts/kill-nvidia &
exec dbus-launch --exit-with-session $WM
#exec $WM

else
 exec $command
fi
